"""Every fact the project states, with the evidence behind it: the Evidence explorer's data.

GenomeOS puts evidence and a confidence on every BioLang block, and the promise is that a
geneticist can see how much of a model is measured and how much is a guess. This module reads
every `.bio` program (the demos, the organism programs, the `bio.std` prelude) and lists one row
per stated fact: which program declares it, what kind of block it is, the evidence kind
(experimental, curated, predicted, inferred, none), its source and its confidence.

A confidence is either stated or UNSTATED, and the two are never pooled. Since review R4
(2026-09-28) the compiler states no confidence on a predicted element or rule, because the size of a
predicted effect is not how sure anyone is, and the parser reads the missing key as 0.0. Counted as a
number, every one of those facts became "weak" overnight (812,921 to 928,094 of 960,096) although
nothing about them had been judged weak: they had stopped being judged at all. A row therefore
carries `stated`, and every count splits into stated-weak, stated-strong and unstated.

A program merges what it imports, so a fact would otherwise be counted once per importer. Each
file is therefore credited only with the facts its imports do not already declare, which is what
"this program states" means.

    from genomeos.evidence import collect
    collect(Path(".")) -> {"rows": [...], "files": [...], "summary": {...}}
"""

from __future__ import annotations

import csv
import io
from functools import lru_cache
from pathlib import Path
from typing import Any

from genomeos.ir import Module, confidence_stated
from genomeos.lang import BioLangError, parse_file
from genomeos.lang.parser import resolve_import

# where programs live: the demos, the organism programs and the standard library
PROGRAM_DIRS = (Path("data/demo"), Path("data/organisms"), Path("genomeos/std"))
# The compiled non-coding programs of area I, one per chromosome, generated by
# scripts/compile_genome_programs.py. They live under the git-ignored knowledge tree because the
# genome's compiled form is 120 MB of generated text - a summary is committed, the text is rebuilt -
# and they are read here when present, because they are where the project's weak evidence actually
# sits: a committed organism program is mostly curated, and these are mostly predicted and inferred.
COMPILED_DIR = Path("data/knowledge/compiled")
KINDS = ("experimental", "curated", "predicted", "inferred", "none")  # strongest first
WEAK = 0.5  # at or below this a fact is worth reviewing; the Program tab uses the same line

BLOCK_FIELDS: dict[str, tuple[str, ...]] = {
    "rule": ("source", "action", "target", "when"),
    "event": ("id", "rate", "rate_unit", "when"),
    "parameter": ("name", "value", "unit"),
    "timer": ("name", "duration", "unit", "when"),
    "stage": ("name", "start", "end", "unit"),
    "decision": ("id", "action", "when", "to"),
    "experiment": ("name", "knockouts", "expect"),
    "field": ("name", "diffusion", "decay"),
    "design": ("name", "targets"),
    "organism": ("name", "species", "tempo"),
}


def _label(block: str, obj: Any) -> str:
    """A short, human-readable name for the fact, in the block's own terms."""
    if block == "rule":
        when = " when " + ", ".join(f"{k}={v}" for k, v in (obj.when or {}).items()) if obj.when else ""
        return f"{obj.source} {obj.action} {obj.target}{when}"
    if block == "parameter":
        return f"{obj.name} = {obj.value}{' ' + obj.unit if obj.unit else ''}"
    if block == "timer":
        return f"{obj.name} {obj.duration} {obj.unit}"
    if block == "stage":
        return f"{obj.name} {obj.start}–{obj.end} {obj.unit}"
    if block == "event":
        effects = ", ".join(
            f"{e.target} {e.op} {e.value:g}{' ' + e.unit if e.unit else ''}" for e in obj.effects
        )
        return f"{obj.id}{': ' + effects if effects else ''}"
    for attr in ("name", "id"):
        if getattr(obj, attr, ""):
            return str(getattr(obj, attr))
    return block


def _detail(block: str, obj: Any) -> dict[str, Any]:
    keys = BLOCK_FIELDS.get(block)
    if keys is None:  # an entity: its own attributes, minus the sequence, which is not a fact about it
        attrs = {k: v for k, v in (getattr(obj, "attrs", {}) or {}).items() if k != "sequence"}
        return {k: v for k, v in attrs.items() if not isinstance(v, (dict, list)) or v}
    out = {}
    for k in keys:
        v = getattr(obj, k, None)
        if v not in (None, "", {}, []):
            out[k] = str(v) if not isinstance(v, (int, float, str)) else v
    return out


def _rows_of(module: Module, path: str) -> list[dict[str, Any]]:
    """One row per fact in a parsed module (including whatever it imported)."""
    rows: list[dict[str, Any]] = []

    def add(block: str, obj: Any) -> None:
        ev = getattr(obj, "evidence", None)
        raw = getattr(obj, "confidence", 0.0)
        rows.append(
            {
                "module": module.name,
                "path": path,
                "block": block,
                "label": _label(block, obj),
                "evidence": ev.kind.value if ev else "none",
                "source": (ev.source if ev else "") or "",
                "organism": (ev.organism if ev else "") or "",
                "note": (ev.note if ev else "") or "",
                # the number stays 0.0 when unstated, for the scripts that read it; `stated` says
                # whether it is a judgement or an absence
                "confidence": round(float(raw or 0.0), 3),
                "stated": confidence_stated(raw),
                "detail": _detail(block, obj),
            }
        )

    for entity in module.entities.values():
        add(entity.kind, entity)
    for block, items in (
        ("rule", module.rules),
        ("event", module.events),
        ("parameter", list(module.parameters.values())),
        ("timer", module.timers),
        ("stage", module.stages),
        ("decision", module.decisions),
        ("experiment", module.experiments),
        ("field", module.fields),
        ("design", module.designs),
    ):
        for obj in items:
            add(block, obj)
    if module.organism is not None:
        add("organism", module.organism)
    return rows


def _identity(row: dict[str, Any]) -> tuple:
    conf = row["confidence"] if row.get("stated", True) else None
    return (row["block"], row["label"], row["evidence"], row["source"], conf)


def _imports_of(path: Path) -> list[Path]:
    """The files a program imports, resolved; schemes (`import protein:TP53`) are not files."""
    try:
        lines = path.read_text().splitlines()
    except OSError:
        return []
    out = []
    for line in lines:  # an import is a top-level line, never inside a block
        code = line.split("#", 1)[0].rstrip()
        if not code.startswith("import "):
            continue
        value = code[len("import ") :].strip()
        if ":" in value:
            continue
        try:
            out.append(resolve_import(value, path.parent))
        except BioLangError:
            continue
    return out


def _own_rows(root: Path, rel: str, seen: frozenset[str] = frozenset()) -> list[dict[str, Any]]:
    """The facts this program declares itself: everything it holds, less what its imports declare."""
    path = root / rel
    if rel in seen:
        return []
    module = parse_file(path)
    rows = _rows_of(module, rel)
    inherited: set[tuple] = set()
    for imported in _imports_of(path):
        try:
            irel = str(imported.relative_to(root))
        except ValueError:
            irel = str(imported)
        inherited.update(_identity(r) for r in _own_rows(root, irel, seen | {rel}))
    return [r for r in rows if _identity(r) not in inherited]


def programs(root: Path, compiled: bool = False) -> list[str]:
    """Every BioLang program in the project, as paths relative to the root.

    The generated chromosome programs are included only on request: parsing them costs about twenty
    seconds, so a page that wants the hand-written programs must not pay for them.
    """
    out: list[str] = []
    for d in (*PROGRAM_DIRS, *((COMPILED_DIR,) if compiled else ())):
        if (root / d).is_dir():
            out.extend(sorted(str(p.relative_to(root)) for p in (root / d).rglob("*.bio")))
    return out


def summarise(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """What the rows say as a whole: how much is measured, how much is a guess."""
    by_evidence: dict[str, int] = {}
    by_block: dict[str, int] = {}
    by_source: dict[str, int] = {}
    for r in rows:
        by_evidence[r["evidence"]] = by_evidence.get(r["evidence"], 0) + 1
        by_block[r["block"]] = by_block.get(r["block"], 0) + 1
        if r["source"]:
            by_source[r["source"]] = by_source.get(r["source"], 0) + 1
    stated = [r for r in rows if r.get("stated", True)]
    conf = [r["confidence"] for r in stated]
    bands = {"0.0–0.3": 0, "0.3–0.5": 0, "0.5–0.7": 0, "0.7–0.9": 0, "0.9–1.0": 0}
    for c in conf:
        key = (
            "0.0–0.3"
            if c < 0.3
            else "0.3–0.5"
            if c < 0.5
            else "0.5–0.7"
            if c < 0.7
            else "0.7–0.9"
            if c < 0.9
            else "0.9–1.0"
        )
        bands[key] += 1
    bands["unstated"] = len(rows) - len(stated)
    # The pooled mean is a mixture and must say so. 2026-09-17's calibration lane tested the
    # predicted band against four measured populations and found the stated level outside its own
    # 95% interval in 10 of 12 bands, with the four offsets pointing in OPPOSITE directions
    # (+0.472, -0.291, -0.137, +0.518). A level is a property of a population, so averaging a
    # curated 0.9, an inferred 0.4 and a predicted effect size into one number produces a figure
    # that is on no scale at all. The pooled mean is kept because callers read it, and the mean per
    # kind is printed beside it so nobody has to take the mixture on trust. Every mean is over the
    # STATED confidences only: an unstated one is an absence, and averaging it in as 0.0 would drag
    # the mean down by however many facts nobody judged. None when nothing was stated.
    by_kind: dict[str, list[float]] = {}
    unstated_by_kind: dict[str, int] = {}
    for r in rows:
        if r.get("stated", True):
            by_kind.setdefault(r["evidence"], []).append(r["confidence"])
        else:
            unstated_by_kind[r["evidence"]] = unstated_by_kind.get(r["evidence"], 0) + 1
    kinds_seen = sorted(set(by_kind) | set(unstated_by_kind), key=lambda k: -by_evidence.get(k, 0))
    weak = sum(1 for c in conf if c <= WEAK)
    return {
        "facts": len(rows),
        "stated": len(stated),
        "unstated": len(rows) - len(stated),
        "weak": weak,
        "strong": len(stated) - weak,
        "mean_confidence": round(sum(conf) / len(conf), 3) if conf else None,
        "mean_confidence_by_evidence": {
            k: {
                "facts": len(by_kind.get(k, [])) + unstated_by_kind.get(k, 0),
                "stated": len(by_kind.get(k, [])),
                "unstated": unstated_by_kind.get(k, 0),
                "mean": round(sum(by_kind[k]) / len(by_kind[k]), 3) if by_kind.get(k) else None,
            }
            for k in kinds_seen
        },
        "mean_confidence_is_a_mixture": (
            "the pooled mean averages curated, inferred and predicted confidences, which the"
            " calibration lane showed are not on one scale: read it with the per-kind means beside it;"
            " every mean is over stated confidences only"
        ),
        "weak_means": f"a STATED confidence at or below {WEAK}; an unstated one is counted apart",
        "unknown_evidence": by_evidence.get("none", 0),
        "by_evidence": dict(sorted(by_evidence.items(), key=lambda kv: -kv[1])),
        "by_block": dict(sorted(by_block.items(), key=lambda kv: -kv[1])),
        "bands": bands,
        "top_sources": dict(sorted(by_source.items(), key=lambda kv: -kv[1])[:12]),
    }


@lru_cache(maxsize=8)
def _cached(
    root: str, stamp: tuple, compiled: bool = False
) -> tuple[tuple[dict[str, Any], ...], tuple[dict[str, Any], ...]]:
    r = Path(root)
    rows: list[dict[str, Any]] = []
    files: list[dict[str, Any]] = []
    for rel in programs(r, compiled):
        try:
            own = _own_rows(r, rel)
        except (BioLangError, OSError) as e:
            files.append({"path": rel, "module": "", "facts": 0, "error": str(e)})
            continue
        rows.extend(own)
        st = [x["confidence"] for x in own if x.get("stated", True)]
        weak = sum(1 for c in st if c <= WEAK)
        files.append(
            {
                "path": rel,
                "module": own[0]["module"] if own else Path(rel).stem,
                "facts": len(own),
                "weak": weak,
                "strong": len(st) - weak,
                "unstated": len(own) - len(st),
                "mean_confidence": round(sum(st) / len(st), 3) if st else None,
            }
        )
    return tuple(rows), tuple(files)


def _stamp(root: Path, compiled: bool = False) -> tuple:
    return tuple(sorted((rel, (root / rel).stat().st_mtime_ns) for rel in programs(root, compiled)))


def collect(
    root: Path,
    kinds: set[str] | None = None,
    max_confidence: float | None = None,
    query: str = "",
    module: str = "",
    compiled: bool = False,
) -> dict[str, Any]:
    """Every stated fact, optionally filtered. The unfiltered summary comes back too, so the page
    can say what share of the whole the filter selected.

    `compiled` decides whether the generated chromosome programs are included. They are excluded by
    default and that is a performance decision with a number behind it: the 24 of them state 940,803
    of the project's 967,426 facts, and reading them takes 21 seconds against under a second for the
    hand-written programs. A page that loaded them by default would be a page nobody opens. The
    headline they carry - 93.6% predicted, 86.4% weak, not one experimental fact - is in
    `evidence_compiled_genome`, and this flag is how the explorer shows the rows behind it.
    """
    all_rows, files = _cached(str(root), _stamp(root, compiled), compiled)
    rows = list(all_rows)
    if kinds:
        rows = [r for r in rows if r["evidence"] in kinds]
    if max_confidence is not None:  # a ceiling on a number the fact must have stated
        rows = [r for r in rows if r.get("stated", True) and r["confidence"] <= max_confidence + 1e-9]
    if module:
        rows = [r for r in rows if r["module"] == module or r["path"] == module]
    if query:
        q = query.lower()
        rows = [
            r
            for r in rows
            if q in r["label"].lower()
            or q in r["source"].lower()
            or q in r["note"].lower()
            or q in r["block"].lower()
            or q in str(r["detail"]).lower()
        ]
    # weakest stated first; the unstated after them, since they carry no judgement to review
    rows.sort(key=lambda r: (not r.get("stated", True), r["confidence"], r["path"], r["block"], r["label"]))
    # A program that fails to parse states no facts, and neither does any program importing it. On
    # 2026-09-27 one demo program with a syntax error took 21 facts out of the total (26,845 to
    # 26,824) and nothing said so. The failures travel beside the rows so every caller can count them.
    failed = [{"path": f["path"], "error": f["error"]} for f in files if f.get("error")]
    # When any program failed, the report ROADMAP item 9 asked for rides beside the rows: each
    # failure's path and message, their count and `complete: false`, so a partial count never passes
    # for the whole, whatever the filter selected. A clean read adds nothing, so every payload of
    # programs that parse stays byte for byte what it was (the discovery view's tests pin
    # /api/evidence by digest); there `failed`, empty, already says nothing failed.
    report = (
        {
            "parse_errors": [{"path": f["path"], "message": f["error"]} for f in failed],
            "parse_error_count": len(failed),
            "complete": False,
        }
        if failed
        else {}
    )
    return {
        "rows": rows,
        "files": list(files),
        "failed": failed,
        **report,
        "summary": summarise(rows),
        "whole": summarise(list(all_rows)),
        "weak_line": WEAK,
        "evidence_kinds": list(KINDS),
    }


def to_csv(rows: list[dict[str, Any]]) -> str:
    """The review list: one line per fact, weakest stated first, "unstated" where none was stated."""
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["confidence", "evidence", "block", "label", "source", "organism", "note", "program"])
    for r in rows:
        w.writerow(
            [
                r["confidence"] if r.get("stated", True) else "unstated",
                r["evidence"],
                r["block"],
                r["label"],
                r["source"],
                r["organism"],
                r["note"],
                r["path"],
            ]
        )
    return out.getvalue()
