# SPDX-License-Identifier: AGPL-3.0-or-later
"""The compiled rule's direction, versioned: v1 as committed, v2 read in the rule's own cell.

**This file is the registration.** Everything below is stated before any count was taken, and the
first commit of this module carries nothing but these constants: no sign is read, no element is
opened, no file is written. The implementation arrives in a later commit and may not restate,
widen or soften a single sentence here.

**The defect.** A compiled rule's direction is the sign of the single most extreme of 371
AlphaGenome tracks: `predict.enhancer_target.predict_target` takes the larger of the biggest drop
and the biggest rise over every track, and `attribution/compile.py` writes `activates` or
`inhibits` from it (`compile.element_axes`, `compile.compile_chromosome`). One track out of 371,
selected for being extreme, decides what the program asserts about molecular action, and the
assertion reads the same whether the effect was large or a hair above `MIN_EFFECT`.

**What v2 changes, and what it does not.** v2 changes what a rule *asserts* about direction. It
proves nothing. No measurement in this lane says a v2 call is right, no agreement rate against any
benchmark is computed here, and nothing here is validation (`NOT_VALIDATION`). v2 is not a gain in
accuracy (`NOT_AN_IMPROVEMENT`); it declines to state a direction the evidence in one cell does not
carry, which is a different claim and a weaker one.

**v1 stays the default and stays byte-identical.** `DIRECTION_RULE_DEFAULT` is `V1`, v1 reproduces
the committed expression exactly, and no compiled program is regenerated by this lane.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from genomeos.predict import enhancer_target as et
from genomeos.predict.enhancer_target import CELLS, MIN_EFFECT

# ---- the versions -------------------------------------------------------------------------------

#: The rule as committed: the sign of the single most extreme of 371 tracks, read off
#: `predicted_coding["action"]`. Selectable, the default, and not modified by this lane.
V1 = 1
#: The rule registered here: the sign in the rule's own assigned cell's retained tracks, or
#: unresolved.
V2 = 2
#: What a caller that states no version gets. It is `V1` and this lane does not change it.
DIRECTION_RULE_DEFAULT = V1

V1_RULE = (
    "v1: the direction is the sign of the single most extreme of the 371 tracks, as "
    "predict.enhancer_target.predict_target selected it - the larger of the biggest drop and the "
    "biggest rise over all tracks, ties to activation - and the compiler writes `activates` when "
    "predicted_coding['action'] == 'activates' and `inhibits` otherwise. A loss of the target's "
    "expression on deleting the element is read as the element activating the gene, a rise as the "
    "element acting the other way, which the compiled activity axis names `represses_target`"
)

# ---- what "the rule's own assigned cell" is ------------------------------------------------------

ASSIGNED_CELL = (
    "the rule's assigned cell is the biosample name of the track the v1 maximum selected, "
    "predicted_coding['tissue']: it is what compile.context() writes into `when: cell_type` on the "
    "rule line, so it is the cell in which the rule asserts its action. When the field is missing or "
    "blank the compiler writes measured.CONTEXT_UNKNOWN and v2 resolves nothing"
)

CELL_EVIDENCE = (
    "v2 reads only the values the cached deletion answer retains for that one cell name on the "
    "target gene's own row, and no value from any other cell: the tracks of other cells are not "
    "evidence about this rule's action in this cell. Three values can be retained per gene row and "
    "no more - max_drop_log2fc when max_drop_tissue is that cell, max_rise_log2fc when "
    "max_rise_tissue is that cell, and by_cell[cell] when the cell is one of "
    f"predict.enhancer_target.CELLS {list(CELLS)}. Each is a signed log2 fold change of the target "
    "gene on deleting the element, from the same sweep, named by its cell"
)

CACHE_IS_LEGACY = (
    "every cached deletion answer in data/knowledge/alphagenome/elements is pre-BY_CELL_SCHEMA 2: "
    "0 of the 24 chromosome archives carries by_cell_summary, so a cell's full multiset of emitted "
    "values is not on disk and cannot be recovered by loading or repacking (the schema-2 note in "
    "predict.enhancer_target says so in those words). by_cell holds the last emitted value per cell "
    "name, which is order-dependent and was not chosen as a replicate. v2 therefore resolves on at "
    "most three retained values per cell and reports unresolved wherever fewer than two are "
    "retained; a resolved v2 call on a legacy row can rest on one order-dependent value beside the "
    "selected extreme, and that is a limitation of the cache and not a strength of the rule"
)

# ---- the sign rule, stated before any count ------------------------------------------------------

#: The magnitude floor, imported as an object and never copied as a literal: the project's own
#: smallest |log2 fold change| that names a target at all (`predict.enhancer_target.MIN_EFFECT`). A
#: value the project will not accept as naming a target cannot be accepted as naming a direction.
#: `tests/test_direction_v2.py` asserts this is the same object by `is`.
MAGNITUDE_FLOOR = MIN_EFFECT

MAGNITUDE_FLOOR_IS_IMPORTED = (
    "the floor is predict.enhancer_target.MIN_EFFECT, the same object, asserted by `is` in the "
    "tests. It was not chosen here and no number was copied: MIN_EFFECT is already the project's "
    "threshold for an effect large enough to name a target, and this registration adopts it "
    "unchanged as the threshold for an effect large enough to name a direction. Nothing in the "
    "repository fixes a consistency threshold, so consistency is not a number at all (see "
    "CONSISTENCY_RULE): it is unanimity, which has nothing to tune"
)

CONSISTENCY_RULE = (
    "consistency is unanimity of sign among the cell's retained values, using "
    "predict.enhancer_target's own definition of disagreement - some value above zero and some "
    "value below zero - imported rather than restated. Unanimity is the strictest available reading "
    "and carries no tunable number, so no count can move it"
)

SIGN_RULE_V2 = (
    "v2 resolves the direction of a rule only when all three hold of its assigned cell's retained "
    "values: (1) at least two values are retained for that cell name, so that no direction rests on "
    "one track - which is the defect v1 has; (2) every retained value has the same sign, no value "
    "is exactly zero, and predict.enhancer_target's signs_disagree is false of them; (3) the "
    "largest |value| is at least MAGNITUDE_FLOOR. The resolved direction is that common sign: "
    "negative - the target falls on deleting the element - resolves to `activates`, positive to "
    "`inhibits`, the same two tokens and the same convention the compiler already writes. In every "
    "other case v2 returns UNRESOLVED"
)

UNRESOLVED_REASONS = (
    # one reason per refusal, recorded on the call; none of them is a direction
    "context_unknown",  # no tissue on the prediction, so the rule names no cell to read
    "no_row_for_target",  # the cached answer holds no row for the gene the rule names
    "one_value_only",  # exactly one value retained for the cell: v1's own selected extreme
    "one_track_seen_twice",  # two retained values, numerically identical: amendment 1
    "no_value_for_cell",  # the cell name appears on no retained value of that row
    "signs_disagree_in_cell",  # the cell's retained values point both ways
    "below_magnitude_floor",  # every retained value is under MAGNITUDE_FLOOR
    "zero_value_in_cell",  # a retained value is exactly zero and so has no sign
)

AMENDMENT_1 = (
    "amendment 1, 2026-10-02, against this lane's own first implementation and not against the "
    "registration. SIGN_RULE_V2 clause (1) says `at least two values are retained for that cell "
    "name, so that no direction rests on one track - which is the defect v1 has`, and the first "
    "implementation did not secure the reason it gives: on a legacy row by_cell[cell] can be the "
    "very track the maximum selected, so two retained fields can carry one track. Measured on "
    "chr21, 271 of 619 resolved calls had two numerically identical values. The implementation now "
    "requires the two retained values to be numerically distinct and records "
    "`one_track_seen_twice` otherwise. The cache records no track identity - "
    "predict.enhancer_target says in those words that none is invented, a value arrives with its "
    "cell name and nothing else - so two distinct tracks that happen to carry the same rounded "
    "value are refused too, which errs towards unresolved and is the direction this rule errs in. "
    "This amendment can only move a call from resolved to unresolved and never the other way, so "
    "it cannot have been chosen to produce a resolution, and it moves no threshold: MAGNITUDE_FLOOR "
    "is still the imported MIN_EFFECT and consistency is still unanimity. Both counts are reported, "
    "before it and after it"
)

UNRESOLVED_MEANS = (
    "unresolved means the sign rule did not resolve. It never means the element has no action, it "
    "is not a measurement of absence, and it is not a failure of the rule to produce an output: an "
    "unresolved call is the correct output of v2 wherever one cell's retained values do not carry a "
    "sign. It is recorded as molecular action unknown"
)

UNRESOLVED_IS_FIRST_CLASS = (
    "UNRESOLVED is a value of its own kind and not a third string beside `activates` and "
    "`inhibits`: it compares equal to neither, it is not a cell name, and reading a direction off a "
    "call that did not resolve raises rather than returning either token. No default, no coercion, "
    "and in particular no fall-through to `activates` because activation is the common case. A "
    "caller that wants a writable token must handle the unresolved case explicitly"
)

# ---- the counts, named in advance ----------------------------------------------------------------

COUNTS_REGISTERED = (
    "over every predicted-layer rule the compiler emits for the named chromosomes - one rule per "
    "attributed element, the population compile.compile_chromosome writes `rule ... activates|"
    "inhibits` for, with the measured layer excluded because a measured rule carries a screen's "
    "effect and no AlphaGenome direction - exactly these counts are reported, separately and "
    "never pooled: (a) v1 calls whose activity axis is `represses_target` that v2 leaves "
    "UNRESOLVED; (b) v1 calls whose activity axis is `activates_target` that v2 leaves UNRESOLVED; "
    "(c) calls v2 resolves to the opposite token from v1, the outright flips; and beside them the "
    "count v2 resolves in agreement with v1, so that the four add up to the population. Every "
    "unresolved call is also counted under its reason from UNRESOLVED_REASONS"
)

FLIPS_ARE_STRUCTURALLY_IMPOSSIBLE = (
    "stated before any count, because it follows from the rule and not from the data: under "
    "SIGN_RULE_V2 the flip count (c) is 0 by construction. v1's own selected value is itself one of "
    "the assigned cell's retained values, and v2 resolves only when every retained value shares one "
    "sign, so a resolved v2 call always carries v1's sign. v2 can therefore withhold a direction "
    "and can never reverse one. This is registered in advance so that a measured 0 is read as the "
    "arithmetic it is and not as evidence that v1's directions are sound"
)

SELECTION_EXCLUDED_DIAGNOSTIC = (
    "one diagnostic is reported beside the counts and is not a v2 output: among v1 calls whose "
    "assigned cell is one of predict.enhancer_target.CELLS, how many have by_cell[cell] of the "
    "opposite sign to the selected extreme. These are the calls a variant that discarded the "
    "selected value as selected would reverse. The variant is not adopted here, because on a legacy "
    "row it would rest the whole direction on one order-dependent track, and the count is reported "
    "as a property of the cache and never as a count of wrong rules"
)

COUNTS_VALIDATE_NOTHING = (
    "neither the unresolved counts nor the flip count validates anything, in either direction. A "
    "large unresolved count is not evidence that v1 was wrong, a small one is not evidence that v1 "
    "was right, and 0 flips is arithmetic (FLIPS_ARE_STRUCTURALLY_IMPOSSIBLE) rather than agreement"
)

# ---- what this lane may not claim ----------------------------------------------------------------

NOT_VALIDATION = (
    "nothing here is validation. v2 reads the same AlphaGenome sweep v1 reads, restricted to one "
    "cell name, so it is a second reading of one model and never independent evidence. No v2 call "
    "has been held against a measured outcome by any method in this lane"
)

NOT_AN_IMPROVEMENT = (
    "v2 is not an improvement in accuracy and this lane has no measurement that would support "
    "calling it one. A rule that is more careful about direction is not thereby more correct about "
    "biology. What changed is that a direction one cell's values do not carry is now recorded as "
    "unknown instead of being asserted"
)

WORDING = (
    "a measured increase on knockdown is an increase on knockdown, and the prohibition on calling "
    "it anything else is attribution.increase_links.check_no_mechanism_claim, which this module "
    "neither copies nor shadows: it defines no word list of its own, and the tests run the imported "
    "checker and plant a counterfactual that it rejects. `not_open_in_reader` means not detected "
    "open at the reader's registered call, never closed. Unresolved means the sign rule did not "
    "resolve, never that the element has no action"
)

# ---- the tokens, and the value that is neither of them --------------------------------------------

#: The two action tokens the compiler writes on a `rule` line. The byte-identity test holds v1's
#: output to the committed program, so these cannot drift from what compile.py used to write.
ACTIVATES = "activates"
INHIBITS = "inhibits"

MOLECULAR_ACTION_UNKNOWN = (
    "molecular action unknown: the sign rule did not resolve in the rule's own assigned cell"
)

V2_NOT_WRITABLE = (
    "the BioLang `rule` head takes one action token and the grammar has none for a direction that "
    "did not resolve, so an unresolved v2 call cannot be written into a program. Writing `inhibits` "
    "or `activates` for it would be the defect v2 exists to stop, so the compiler refuses instead. "
    "Adding a token is a change to the grammar and to every compiled program, which this lane does "
    "not make"
)


class UnresolvedDirectionError(Exception):
    """Raised when a direction is read off a call that did not resolve. Never caught in this module."""


class _Unresolved:
    """The unresolved direction, as a value of its own kind.

    It equals nothing but itself, so `call.token == ACTIVATES` and `call.token == INHIBITS` are both
    false and `call.token in (ACTIVATES, INHIBITS)` is false. `bool()` raises rather than answering,
    so `if token:` cannot quietly read it as a direction. There is one instance.
    """

    __slots__ = ()
    _instance: _Unresolved | None = None

    def __new__(cls) -> _Unresolved:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __repr__(self) -> str:
        return "UNRESOLVED"

    def __str__(self) -> str:
        return "UNRESOLVED"

    def __eq__(self, other: object) -> bool:
        return other is self

    def __ne__(self, other: object) -> bool:
        return other is not self

    def __hash__(self) -> int:
        return hash("genomeos.attribution.direction_v2.UNRESOLVED")

    def __bool__(self) -> bool:
        raise UnresolvedDirectionError(UNRESOLVED_IS_FIRST_CLASS)


#: The unresolved direction. `UNRESOLVED_MEANS` says what it means and what it does not.
UNRESOLVED = _Unresolved()


@dataclass(frozen=True)
class DirectionCall:
    """One rule's direction under one version of the rule, with the evidence it was read from."""

    version: int
    token: str | _Unresolved
    cell: str
    values: tuple[tuple[str, float], ...] = ()
    reason: str | None = None

    @property
    def resolved(self) -> bool:
        return self.token is not UNRESOLVED

    @property
    def action(self) -> str:
        """The token the compiler would write, or `UnresolvedDirectionError`. There is no third return."""
        if self.token is UNRESOLVED:
            raise UnresolvedDirectionError(f"{self.reason}: {V2_NOT_WRITABLE}")
        assert isinstance(self.token, str)
        return self.token

    @property
    def molecular_action(self) -> str:
        """What the call says about molecular action: a token, or that it is unknown."""
        return MOLECULAR_ACTION_UNKNOWN if self.token is UNRESOLVED else self.action

    def to_dict(self) -> dict[str, Any]:
        return {
            "direction_rule_version": self.version,
            "molecular_action": self.molecular_action,
            "resolved": self.resolved,
            "assigned_cell": self.cell,
            "values_in_assigned_cell": [[s, v] for s, v in self.values],
            "unresolved_reason": self.reason,
        }


# ---- v1: the committed rule, unchanged -------------------------------------------------------------


def _v1(pc: dict[str, Any]) -> DirectionCall:
    """`activates` when predicted_coding['action'] == 'activates', `inhibits` otherwise. As committed."""
    token = ACTIVATES if pc.get("action") == "activates" else INHIBITS
    return DirectionCall(version=V1, token=token, cell=pc.get("tissue") or "")


# ---- v2: the sign in the rule's own assigned cell ---------------------------------------------------


def retained_values(row: dict[str, Any], cell: str) -> tuple[tuple[str, float], ...]:
    """Every value the cached gene row retains for one cell name, with the field it came from.

    `CELL_EVIDENCE` names the three and says there are no others on a legacy row. A value whose
    tissue field is empty belongs to no cell and is never matched, so the zero a gene row carries
    for a direction no track took is not read as a value of any cell.
    """
    out: list[tuple[str, float]] = []
    if cell and row.get("max_drop_tissue") == cell:
        out.append(("max_drop", float(row["max_drop_log2fc"])))
    if cell and row.get("max_rise_tissue") == cell:
        out.append(("max_rise", float(row["max_rise_log2fc"])))
    by_cell = row.get("by_cell") or {}
    if cell and by_cell.get(cell) is not None:
        out.append(("by_cell", float(by_cell[cell])))
    return tuple(out)


def _signs_disagree(values: list[float]) -> bool:
    """`predict.enhancer_target`'s own reading of disagreement, imported and not restated."""
    return bool(et._cell_summary(values)["signs_disagree"])


def _v2(pc: dict[str, Any], row: dict[str, Any] | None) -> DirectionCall:
    """`SIGN_RULE_V2`, word for word: two values, one sign, over the floor, or UNRESOLVED."""
    cell = pc.get("tissue") or ""
    if not cell.strip():
        return DirectionCall(V2, UNRESOLVED, "", (), "context_unknown")
    if row is None:
        return DirectionCall(V2, UNRESOLVED, cell, (), "no_row_for_target")
    found = retained_values(row, cell)
    values = [v for _, v in found]
    if not values:
        return DirectionCall(V2, UNRESOLVED, cell, found, "no_value_for_cell")
    if len(values) < 2:
        return DirectionCall(V2, UNRESOLVED, cell, found, "one_value_only")
    if len(set(values)) < 2:  # AMENDMENT_1: two fields, one track
        return DirectionCall(V2, UNRESOLVED, cell, found, "one_track_seen_twice")
    if any(v == 0.0 for v in values):
        return DirectionCall(V2, UNRESOLVED, cell, found, "zero_value_in_cell")
    if _signs_disagree(values):
        return DirectionCall(V2, UNRESOLVED, cell, found, "signs_disagree_in_cell")
    if max(abs(v) for v in values) < MAGNITUDE_FLOOR:
        return DirectionCall(V2, UNRESOLVED, cell, found, "below_magnitude_floor")
    token = INHIBITS if values[0] > 0 else ACTIVATES
    return DirectionCall(V2, token, cell, found)


# ---- the dispatch, and the seam the compiler calls ---------------------------------------------------


def direction_call(
    pc: dict[str, Any],
    version: int = DIRECTION_RULE_DEFAULT,
    *,
    chrom: str | None = None,
    element_id: str | None = None,
    row: dict[str, Any] | None = None,
) -> DirectionCall:
    """The direction of one predicted rule under `version`.

    v1 reads nothing but `pc` and opens no file, so the default path costs what it always cost. v2
    needs the target gene's cached row: it is taken from `row` when given, else from the deletion
    cache for `chrom`/`element_id`, which is read from disk and never from the model.
    """
    if version == V1:
        return _v1(pc)
    if version != V2:
        raise ValueError(f"no direction rule version {version!r}; the versions are {V1} and {V2}")
    if row is None and chrom and element_id:
        row = cached_row(chrom, element_id, pc.get("gene"))
    return _v2(pc, row)


def compiled_action(
    pc: dict[str, Any],
    version: int = DIRECTION_RULE_DEFAULT,
    *,
    chrom: str | None = None,
    element_id: str | None = None,
) -> str:
    """The action token the compiler writes, or `UnresolvedDirectionError` when the rule did not resolve.

    This is the one seam: `compile.element_axes` and `compile.compile_chromosome` read their
    direction here and nowhere else. Under `V1` it returns exactly what the two committed
    expressions returned, which `tests/test_direction_v2.py` holds to the compiled program byte for
    byte. Under `V2` an unresolved call raises `V2_NOT_WRITABLE` rather than naming a direction.
    """
    return direction_call(pc, version, chrom=chrom, element_id=element_id).action


# ---- the cached rows, read from disk ---------------------------------------------------------------


def cached_row(chrom: str, element_id: str, gene: str | None) -> dict[str, Any] | None:
    """The cached gene row for one element's named target, or None.

    `predict.enhancer_target.load_cached` is the project's own reader and is used unchanged: the
    per-element file when there is one, else the chromosome's packed archive, which it reads once per
    process. Disk only - 0 model requests, no network, no money.
    """
    answer = et.load_cached(chrom, element_id)
    if not answer or not gene:
        return None
    for row in answer.get("genes", []):
        if row.get("gene") == gene:
            return row
    return None
