# SPDX-License-Identifier: AGPL-3.0-or-later
"""Register, before any concordance is computed, whether a rule's cell is the element's or the
gene's.

    uv run --frozen python scripts/label_gene_register.py

Writes data/results/label_gene_registration.json through save_result. The file is committed ON ITS
OWN, before scripts/label_gene_count.py exists, because "registered first" has to rest on git and
not on a lane's word.

What it binds, all of it before the observed side exists:

1. THE QUESTION, and the clause saying what this population CANNOT answer: with one gene per
   element the symmetric within-ELEMENT test cannot be run at all, so a result at the control level
   means "not a gene property" and never "an element property".
2. THE PRIMARY statistic, and that the unit of analysis is GENES and not pairs.
3. CONTROL 1, the sum of p squared over chr21's own compiled label distribution - not the track
   count - quoted beside every ratio.
4. CONTROL 2, the distance-matched different-gene arm, with the bin edges and the tolerance fixed
   here.
5. THE RELATIVE BANDS and the four readings (a), (a'), (b), (c), with (c)'s words fixed as "the
   data cannot tell".
6. THE INSTRUMENT: genes as clusters, the dyadic cluster bootstrap for different-gene pairs, the
   degenerate route, and the identical-resample share reported for every interval.
7. POWER per comparison, in genes.
8. THE SECONDARY GTEx arm with its training-exposure caveat.
9. The RSS ceiling that RAISES, and the declared input hashes.

No element table is parsed, no label is counted, no concordance is computed. 0 model requests, no
network, no money.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from genomeos import manifest as mf  # noqa: E402
from genomeos.attribution import label_gene as lg  # noqa: E402

RESULT = "label_gene_registration"
WILL_WRITE = "data/results/label_gene.json"

BIO = Path("data/organisms/human/noncoding_chr21.bio")
GTEX = Path("data/cache/c5/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz")

#: This lane's own files. Everything else uncommitted in this shared checkout belongs to a peer.
OWN_CODE = (
    "genomeos/attribution/label_gene.py",
    "scripts/label_gene_register.py",
    "scripts/label_gene_count.py",
    "tests/test_label_gene.py",
)


def inputs() -> list[dict[str, Any]]:
    """The two named files the run will read, digested here so the result cannot be read against a
    different input than the one registered."""
    out: list[dict[str, Any]] = []
    if BIO.exists():
        out.append(
            mf.input_entry(
                BIO,
                partition="the committed compiled chr21 non-coding program. Read line by line for "
                "`element <id> {`, its `locus:` and its predicted `rule` line's element, gene and "
                "`when: cell_type` only. No bulk chromosome archive is opened and no "
                "cached-element loader is called",
            )
        )
    if GTEX.exists():
        out.append(
            mf.input_entry(
                GTEX,
                partition="GTEx v8 gene median TPM, the SECONDARY arm's input. Its tracks are the "
                "same RNA-seq AlphaGenome's GTEx tracks were trained on, which is the registered "
                "training-exposure caveat",
            )
        )
    return out


def payload() -> dict[str, Any]:
    entries = inputs()
    body = lg.registration()
    body["what_the_run_will_write"] = WILL_WRITE
    body["alphagenome_requests"] = 0
    body["money"] = "none: no request is sent and no key is read"
    body["result_manifest"] = {
        "sources": [
            {
                "accession": "the committed compiled program data/organisms/human/"
                "noncoding_chr21.bio, generated by `genomeos budget --chrom chr21 --bio`",
                "version": "the committed file on this machine, digested in inputs",
            },
            {
                "accession": "GTEx v8 GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm",
                "version": "the cached file on this machine, digested in inputs. SECONDARY arm "
                "only, and under the registered training-exposure caveat",
            },
        ],
        "inputs": entries,
        "input_count": len(entries),
        "assembly": "GRCh38: the assembly the compiled program's element loci are on. This "
        "registration computes no coordinate of its own",
        "coordinates": {
            "base": 0,
            "interval": "half-open",
            "note": "the element blocks' own `locus: chr21:start-end`, used only for the midpoint "
            "that defines element-to-element distance. This registration reads no interval",
        },
        "parameters": {
            "band_at_control": list(lg.BAND_AT_CONTROL),
            "band_far_above": lg.BAND_FAR_ABOVE,
            "distance_bin_edges_bp": [
                int(e) if e != float("inf") else "inf" for e in lg.DISTANCE_BIN_EDGES_BP
            ],
            "minimum_pairs_per_bin": lg.MIN_PAIRS_PER_BIN,
            "maximum_dropped_matching_weight": lg.MAX_DROPPED_WEIGHT,
            "minimum_clusters_genes": lg.MIN_CLUSTERS,
            "bootstraps": lg.BOOTSTRAPS,
            "minimum_resamples": lg.MIN_RESAMPLES,
            "seed": lg.SEED,
            "rss_ceiling_bytes": lg.RSS_CEILING_BYTES,
            "no_threshold_of_any_rule_is_set_or_moved": "no test, threshold, pin or registration "
            "anywhere in the repository is weakened, exempted or allowlisted by this lane, and no "
            ".bio file, compiler, IR, grammar or parser file is touched. The only numbers this "
            "lane sets are its own reading bands, and they are set here before any figure exists",
        },
        "exclusions": [
            "the two rule lines carrying `experimental`: their cell is the cell an assay was run "
            "in and not an argmax, so they are not this lane's object",
            "every `_measured` element block: it raises no predicted rule and carries no argmax label",
            "every gene carrying one element: it forms no within-gene pair. Such a gene still "
            "contributes its element to the different-gene arm",
            "every distance bin holding fewer than the registered minimum of pairs in either arm: "
            "its within-gene weight is dropped and the dropped weight is reported",
            "every rule whose normalised label matches no GTEx column, from the SECONDARY arm's "
            "denominator only",
            "every bulk chromosome archive and every cached-element loader call: none is made",
        ],
        "partitions": {
            "within_gene_pairs": "the PRIMARY denominator: unordered pairs of elements sharing one "
            "target gene, pooled over genes, with genes as the resampling clusters",
            "different_gene_pairs": "CONTROL 2's denominator: unordered pairs of elements of "
            "different genes, aggregated per gene pair per distance bin and reweighted to the "
            "within-gene distance distribution",
            "control_1": "no denominator of its own: a committed constant, the sum of p squared "
            "over this population's label distribution",
            "gtex_secondary": "the rules whose label is a GTEx tissue and whose gene is in the "
            "GTEx matrix. SECONDARY, and never the headline",
        },
        "code_cleanliness": mf.code_cleanliness(__file__, OWN_CODE),
    }
    return body


def main() -> int:
    from genomeos.results import save_result

    body = payload()
    path = save_result(RESULT, body)
    print(f"registered: {path}")
    print("  control 1: sum of p squared over chr21's own compiled label distribution")
    print(f"  bands: at control {body['band_at_control']}, far above > {body['band_far_above']}")
    print(f"  clusters: GENES, floor {body['min_clusters_genes']}")
    print(f"  distance bins (bp): {body['distance_bin_edges_bp']}")
    print(f"the run will write: {WILL_WRITE}")
    print("no concordance computed; 0 model requests, no network, no money")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
