# SPDX-License-Identifier: AGPL-3.0-or-later
"""What adopting the rule-evidence-tier mark would cost, counted over the `.bio` corpus.

    uv run --frozen python scripts/rule_evidence_tier_cost.py            # hand-authored only
    uv run --frozen python scripts/rule_evidence_tier_cost.py --scan     # + the generated corpus

It counts and it recommends nothing. It writes no file, edits no `.bio` and changes no number.

TWO INSTRUMENTS, and they are not equally good, which is why both are run rather than one trusted:

* a PARSE of each hand-authored program through `genomeos.lang.parser.parse_file`, which is exact;
* a streaming LINE SCAN for `rule <Source> <action> <Target>` headers, which is weaker - it can
  undercount a wrapped header and overcount a header inside a string - but is the only instrument
  that fits the generated corpus, 399 MB of it, inside bounded memory.

THE TWO DISAGREED, AND THE DISAGREEMENT IS A FINDING RATHER THAN A BUG IN EITHER. They count
different populations. The parse counts the rules THE COMPILER SEES, which is more than the program
writes: the parser SYNTHESISES a `produces` rule from every `gene ... { produces: ... }` clause, and
each one carries `strength`, `threshold` and `hill` at the language defaults of
`genomeos/ir/model.py` - numbers no line of the program states. `data/demo/gastrulation.bio` writes
7 rules and compiles to 11 for that reason. So three populations are reported, not two:
`rules_written` (scanned), `rules_compiled` (parsed), and `rules_with_tiered_numbers` (parsed, then
filtered to the actions whose numbers are actually read - see `rule_evidence_tier.TIERED_ACTIONS`).
The scan is calibrated against the THIRD, and the first calibration run found the scan's identifier
pattern too narrow to match `rule Nkx2-5 activates MYH6`, which is what a calibration is for.

The generated corpus is never parsed: `data/knowledge` alone is ~399 MB and a lane paged this
machine tonight with an inline loop over data of that order.

CLASSIFICATION is a heuristic and is reported per file so a reader can check it, never as a verdict:
a program counts as generated when its first lines say a tool wrote it, or when it is git-ignored
(a file too large to track is not hand-authored). Everything else counts as hand-authored. The
distinction matters because only hand-authored rules would need a human to decide a tier; a
generated rule gets whatever its compiler writes, and a compiler can be changed once.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from genomeos.lang import rule_evidence_tier as ret  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

#: Where the corpus lives. `build/` is excluded: it holds packaging copies of files counted already.
ROOTS = ("data/demo", "genomeos/std", "data/organisms", "data/knowledge")

#: A `rule` header as the grammar writes it: `rule <Source> <action> <Target>`.
#: Identifiers may carry `-` and `.` (`rule Nkx2-5 activates MYH6`), which the first pattern here
#: did not allow; the calibration against the parse is what caught it.
RULE_HEADER = re.compile(
    r"^\s*rule\s+[\w.-]+\s+(activates|inhibits|modifies|produces|binds|degrades)\s+[\w.-]+"
)

#: First lines that say a tool wrote the file. Matched case-insensitively over the leading comments.
GENERATED_MARKERS = ("generated by", "generated on", "compiled by", "written by `genomeos", "--bio`")

HEADER_LINES = 12


def bio_files() -> list[Path]:
    out: list[Path] = []
    for r in ROOTS:
        out.extend(sorted((ROOT / r).rglob("*.bio")))
    return [p for p in out if "build" not in p.relative_to(ROOT).parts]


def is_ignored(path: Path) -> bool:
    rel = str(path.relative_to(ROOT))
    return (
        subprocess.run(["git", "-C", str(ROOT), "check-ignore", "-q", rel], capture_output=True).returncode
        == 0
    )


def classify(path: Path) -> tuple[str, str]:
    """`("generated"|"hand_authored", the reason)`. A heuristic, and the reason is reported with it."""
    with path.open(encoding="utf-8", errors="replace") as fh:
        head = "".join(next(fh, "") for _ in range(HEADER_LINES)).lower()
    for marker in GENERATED_MARKERS:
        if marker in head:
            return "generated", f"its header says {marker!r}"
    if is_ignored(path):
        return "generated", "git-ignored: a file too large to track is not hand-authored"
    return "hand_authored", "no generator marker in its first lines and it is tracked"


def scan_rules(path: Path) -> int:
    """Rule headers by streaming line scan: one line held at a time, whatever the file's size."""
    n = 0
    with path.open(encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if RULE_HEADER.match(line):
                n += 1
    return n


#: How a synthesised rule is told from a written one, stated rather than guessed: the parser names a
#: rule it synthesises from a `produces` clause `<GENE>-><Protein>`, while a written rule is named
#: `<source> <action> <target>` or by its own `id:`. A test requires this to give 7 written and 4
#: synthesised on data/demo/gastrulation.bio, so the criterion is checked and not asserted.
SYNTHESISED_ID = "->"


def parse_rules(path: Path) -> tuple[int, int, int]:
    """`(compiled, written by the program, with tiered numbers)`.

    `compiled` is every rule the parser produces; `written` excludes the ones it synthesises from
    `gene { produces: ... }` clauses; `with tiered numbers` is the tier population, the rules whose
    strength, threshold and hill the GRN runtime reads.
    """
    from genomeos.lang.parser import parse_file

    rules = parse_file(path).rules
    written = [r for r in rules if SYNTHESISED_ID not in r.id]
    return len(rules), len(written), len(ret.tiered_rules(rules))


def cost(scan_generated: bool = True) -> dict[str, Any]:
    files: list[dict[str, Any]] = []
    for p in bio_files():
        kind, why = classify(p)
        rel = str(p.relative_to(ROOT))
        rec: dict[str, Any] = {"path": rel, "kind": kind, "why": why, "bytes": p.stat().st_size}
        if kind == "hand_authored":
            compiled, written, tiered = parse_rules(p)
            rec["rules_compiled"] = compiled
            rec["rules_written"] = written
            rec["rules_with_tiered_numbers"] = tiered
            rec["rules_synthesised_by_the_parser"] = compiled - written
            rec["rules_scanned"] = scan_rules(p)
        elif scan_generated:
            rec["rules_scanned"] = scan_rules(p)
        files.append(rec)

    hand = [f for f in files if f["kind"] == "hand_authored"]
    gen = [f for f in files if f["kind"] == "generated"]
    disagreements = [
        {"path": f["path"], "written": f["rules_written"], "scanned": f["rules_scanned"]}
        for f in hand
        if f["rules_written"] != f["rules_scanned"]
    ]
    hand_rules = sum(f["rules_with_tiered_numbers"] for f in hand)
    hand_compiled = sum(f["rules_compiled"] for f in hand)
    hand_written = sum(f["rules_written"] for f in hand)
    hand_synth = sum(f["rules_synthesised_by_the_parser"] for f in hand)
    hand_with_rules = sum(1 for f in hand if f["rules_with_tiered_numbers"])
    gen_rules = sum(f.get("rules_scanned", 0) for f in gen) if scan_generated else None

    slots_per_rule = len(ret.TIERED_FIELDS)
    return {
        "proposal": "rule_evidence_tier",
        "what_this_is": "the adoption cost, counted. No recommendation; the decision is Albert's.",
        "not_blind": ret.NOT_BLIND,
        "default": ret.NOT_ASSESSED,
        "slots_per_rule": slots_per_rule,
        "files": files,
        "programs_total": len(files),
        "programs_hand_authored": len(hand),
        "programs_hand_authored_with_at_least_one_rule": hand_with_rules,
        "programs_generated": len(gen),
        "rules_hand_authored_with_tiered_numbers": hand_rules,
        "rules_hand_authored_compiled": hand_compiled,
        "rules_hand_authored_written": hand_written,
        "rules_hand_authored_synthesised_by_the_parser": hand_synth,
        "synthesised_rules_carry_language_defaults": (
            "each synthesised `produces` rule carries strength 1.0, threshold 1.0 and hill 2.0 from "
            "the `genomeos/ir/model.py` dataclass defaults, written in no program. They are OUTSIDE "
            "the tier population because `genomeos/runtime/grn.py` never reads them: it keeps only "
            f"`r.source` for a PRODUCE rule ({hand_synth} such rules in the hand-authored corpus, "
            f"{hand_synth * slots_per_rule} inert numbers). A test perturbs them and shows the "
            "trajectory does not move, so this rests on the runtime's behaviour and not on a "
            "reading of its source."
        ),
        "slots_hand_authored": hand_rules * slots_per_rule,
        "rules_generated_scanned": gen_rules,
        "slots_generated": None if gen_rules is None else gen_rules * slots_per_rule,
        "scan_calibration": {
            "instrument": "line scan of rule headers against rules_written (the parse, minus "
            "the rules the parser synthesises), on the hand-authored programs",
            "why_not_against_the_tier_population": (
                "a written rule need not carry tiered numbers: data/organisms/human/erythrocyte.bio "
                "writes two `binds` rules, which the scan correctly finds and which the GRN runtime "
                "reads no strength, threshold or hill from. Calibrating against the tier population "
                "would have reported that correct scan as an error."
            ),
            "files_compared": len(hand),
            "disagreements": disagreements,
            "calibrated": not disagreements,
            "if_not_calibrated": (
                "the generated figure is a scan result and not a count, and is reported as such"
            ),
        },
        "generated_corpus_not_parsed": (
            "data/knowledge alone is ~399 MB of `.bio`. It is scanned line by line in bounded "
            "memory and never parsed, so this script cannot page the machine."
        ),
        "day_one_state": (
            f"every slot in the corpus reads `{ret.NOT_ASSESSED}` on the day this is adopted, "
            "including the 21 of data/demo/gastrulation.bio, until the census at 4d4003d is "
            "transcribed into that program. That is the honest state and it is the point rather "
            "than a defect: the alternative defaults each assert something no artefact supports."
        ),
        "what_a_human_would_have_to_decide": (
            "only the hand-authored slots. A generated rule gets whatever its compiler writes, so "
            "the generated corpus costs one change per generator, not one decision per rule - but "
            "every such compiler must then be given a tier to write, and a compiler that writes "
            f"anything other than `{ret.NOT_ASSESSED}` is making a claim it has to be able to support."
        ),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--scan", action="store_true", help="also scan the generated corpus (~399 MB)")
    args = ap.parse_args(argv)
    c = cost(scan_generated=args.scan)
    print(f"programs: {c['programs_total']} ({c['programs_hand_authored']} hand-authored, ")
    print(f"          {c['programs_generated']} generated)")
    print(f"hand-authored rules with tiered numbers (parsed): {c['rules_hand_authored_with_tiered_numbers']}")
    print(
        f"  of {c['rules_hand_authored_written']} written and "
        f"{c['rules_hand_authored_compiled']} compiled; "
        f"{c['rules_hand_authored_synthesised_by_the_parser']} synthesised `produces` rules "
        "carry language defaults and are not read"
    )
    print(f"hand-authored slots to decide: {c['slots_hand_authored']}")
    print(f"  in {c['programs_hand_authored_with_at_least_one_rule']} programs that carry a rule")
    print(f"scan calibrated against the parse: {c['scan_calibration']['calibrated']}")
    if c["scan_calibration"]["disagreements"]:
        print(f"  disagreements: {c['scan_calibration']['disagreements']}")
    if c["rules_generated_scanned"] is None:
        print("generated rules: not scanned (pass --scan)")
    else:
        print(f"generated rules (line scan): {c['rules_generated_scanned']}")
        print(f"generated slots: {c['slots_generated']}")
    print(f"default for every one of them: {c['default']}")
    print("0 .bio files written, 0 numbers changed, 0 model requests, no recommendation")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
